#!/bin/bash

cd /Users/glenshewchuck/Sites/gs

composer -v require \
drupal/paragraphs \
drupal/adminimal_theme \
drupal/admin_toolbar \
drupal/search_api \
drupal/search_api_attachments \
drupal/search_api_autocomplete \
drupal/google_analytics_search_api_autocomplete \
drupal/better_exposed_filters \
drupal/fullcalendar_view \
drupal/linkit \
drupal/colorbox \
drupal/conditional_fields \
drupal/context \
drupal/context_groups \
drupal/term_condition \
drupal/context_entity_field \
drupal/menu_block \
drupal/context_ui \
drupal/date_recur \
drupal/devel \
drupal/diff \
drupal/draggableviews \
drupal/eck \
drupal/environment_indicator \
drupal/facets \
drupal/feeds \
drupal/feeds_tamper \
drupal/paragraphs \
drupal/field_group \
drupal/field_permissions \
drupal/filter_perms \
drupal/flood_unblock \
drupal/focal_point \
drupal/geolocation \
drupal/hierarchical_term_formatter \
drupal/high_contrast \
drupal/insert_block \
drupal/insert_view \
drupal/job_scheduler \
drupal/js_injector \
drupal/libraries \
drupal/address \
drupal/geofield \
drupal/geocoder \
drupal/geolocation \
drupal/maillog \
drupal/masquerade \
drupal/media_bulk_upload \
drupal/metatag \
drupal/module_filter \
drupal/entity_clone \
drupal/office_hours \
drupal/override_node_options \
drupal/pathauto \
drupal/protected_pages \
drupal/protocol_relative_urls \
drupal/queue_ui \
drupal/redirect \
drupal/rules \
drupal/spamspan \
drupal/taxonomy_manager \
drupal/term_reference_tree \
drupal/text_resize \
drupal/ultimate_cron \
drupal/views_block_filter_block \
drupal/views_bulk_operations \
drupal/views_conditional \
drupal/views_data_export \
drupal/views_date_format_sql \
drupal/views_field_view \
drupal/views_url_alias_node \
drupal/webform 

