#!/bin/bash

cd /Users/glenshewchuck/Sites/gs/web


drush -y en paragraphs
#drush -y en adminimal_theme
drush -y en admin_toolbar
drush -y en search_api
drush -y en search_api_attachments
drush -y en search_api_autocomplete
drush -y en google_analytics_search_api_autocomplete
drush -y en better_exposed_filters
drush -y en fullcalendar_view
drush -y en linkit
drush -y en colorbox
drush -y en conditional_fields
drush -y en context
drush -y en context_groups
drush -y en term_condition
drush -y en context_entity_field
drush -y en menu_block
drush -y en context_ui
#drush -y en customfilter
drush -y en date_recur
drush -y en devel
drush -y en diff
drush -y en draggableviews
drush -y en eck
drush -y en environment_indicator
drush -y en facets
drush -y en feeds
drush -y en feeds_tamper
drush -y en paragraphs
drush -y en field_group
drush -y en field_permissions
drush -y en filter_perms
drush -y en flood_unblock
drush -y en focal_point
drush -y en geolocation
drush -y en hierarchical_term_formatter
#drush -y en high_contrast
drush -y en insert_block
drush -y en insert_view
drush -y en job_scheduler
drush -y en js_injector
drush -y en libraries
drush -y en address
drush -y en geofield
drush -y en geocoder
drush -y en geolocation
drush -y en maillog
drush -y en masquerade
drush -y en media_bulk_upload
drush -y en metatag
drush -y en module_filter
drush -y en entity_clone
drush -y en office_hours
drush -y en override_node_options
drush -y en pathauto
drush -y en protected_pages
drush -y en protocol_relative_urls
drush -y en queue_ui
drush -y en redirect
drush -y en rules
drush -y en spamspan
drush -y en taxonomy_manager
drush -y en term_reference_tree
drush -y en text_resize
drush -y en ultimate_cron
drush -y en views_block_filter_block
drush -y en views_bulk_operations
drush -y en views_conditional
drush -y en views_data_export
drush -y en views_date_format_sql
drush -y en views_field_view
drush -y en views_url_alias_node
drush -y en webform
drush -y en field_group_migrate
drush -y en media
drush -y en media_library
